version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./model.gguf:/root/model.gguf
      - ./Modelfile:/root/Modelfile
    command: >
      sh -c "
        if [ -f /root/model.gguf ]; then
          echo 'Model file found, creating Ollama model...'
          ollama create custom-model -f /root/Modelfile
        else
          echo 'Model file not found'
        fi
        ollama serve
      "

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama 